### ISSUE TITLE
Build amd64 wheels for windows

### ISSUE THREAD

**Issue by Cranyozen** [samuelcolvin/rtoml#74]
This is a great project, I like it!
It would be nice if the releases can contain amd64 wheels for windows too.
Otherwise setuptools-rust must be present to continue the installation.

**Comment by samuelcolvin** [comment]
PR welcome to add it.

By the way, `setuptools-rust` isn't used, and `maturin` will be installed as a build requirement. The only external dependency is the rust toolchain.

**Comment by zerocewl** [comment]
maybe fixed with https://github.com/samuelcolvin/rtoml/pull/75 ?

the build wheels pipeline `CI / build os` is skipped, so i can't check which wheels are created

**Comment by zerocewl** [comment]
Seems to be with #75, the pipeline contains now `...win_amd64.whl` wheels again.

https://github.com/samuelcolvin/rtoml/actions/runs/7672121379/job/20911941988

```sh
  Compiling pyo3-build-config v0.20.0
   Compiling pyo3-ffi v0.20.0
   Compiling pyo3 v0.20.0
   Compiling rtoml v0.10.0 (D:\a\rtoml\rtoml)
    Finished release [optimized] target(s) in 14.90s
📦 Built wheel for CPython 3.11 to dist\rtoml-0.10.0-cp311-none-win_amd64.whl
```

**Comment by mirrorcoloured** [comment]
Any updates on when this will be released? I'm still encountering issues building on Windows after updating rust:
```
$ rustup upgrade
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.77.1 (7cf61ebde 2024-03-27)

info: cleaning up downloads & tmp directories

$ python -m pip install rtoml
Collecting rtoml
  Using cached rtoml-0.10.0.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: rtoml
  Building wheel for rtoml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for rtoml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      Running `maturin pep517 build-wheel -i D:\.venv\Scripts\python.exe --compatibility off`
      ðŸ“¦ Including license file "C:\Users\Mirro\AppData\Local\Temp\pip-install-01uskn36\rtoml_4c0e12505933465598c2aeda4980008a\LICENSE"
      ðŸ\x8d¹ Building a mixed python/rust project
      ðŸ”— Found pyo3 bindings
      ðŸ\x90\x8d Found CPython 3.10 at D:\.venv\Scripts\python.exe
      ðŸ“¡ Using build options features, bindings from pyproject.toml
         Compiling autocfg v1.1.0
         Compiling target-lexicon v0.12.3
         Compiling once_cell v1.16.0
         Compiling proc-macro2 v1.0.70
         Compiling unicode-ident v1.0.12
         Compiling windows_x86_64_msvc v0.36.1
         Compiling cfg-if v1.0.0
         Compiling parking_lot_core v0.9.3
         Compiling libc v0.2.125
         Compiling serde v1.0.137
         Compiling version_check v0.9.4
         Compiling smallvec v1.8.0
         Compiling scopeguard v1.1.0
         Compiling heck v0.4.1
         Compiling hashbrown v0.11.2
         Compiling indoc v2.0.4
         Compiling getrandom v0.2.8
      error: linking with `link.exe` failed: exit code: 1
        |
        = note: "link.exe" "/NOLOGO" "C:\\Users\\Mirro\\AppData\\Local\\Temp\\rustcujQdcl\\symbols.o" "C:\\Users\\Mirro\\AppData\\Local\\Temp\\pip-install-01uskn36\\rtoml_4c0e12505933465598c2aeda4980008a\\target\\release\\build\\windows_x86_64_msvc-6b4fb174ad3d4709\\build_script_build-6b4fb174ad3d4709.build_script_build.b126910fc4f5e3e8-cgu.0.rcgu.o" "C:\\Users\\Mirro\\AppData\\Local\\Temp\\pip-install-01uskn36\\rtoml_4c0e12505933465598c2aeda4980008a\\target\\release\\build\\windows_x86_64_msvc-6b4fb174ad3d4709\\build_script_build-6b4fb174ad3d4709.3qijafyczgwxcnvr.rcgu.o" "/LIBPATH:C:\\Users\\Mirro\\AppData\\Local\\Temp\\pip-install-01uskn36\\rtoml_4c0e12505933465598c2aeda4980008a\\target\\release\\deps" "/LIBPATH:C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-af7a289140bfd09b.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-804f96e85949d3c7.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-d732e2e30f000f5c.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-245c07b81320e419.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-071209d3d999dcc9.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-f692450d6626dc45.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-80b2971dd5ef99d4.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-9b96265a2194d52d.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-9f5f4b367cf5c108.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-1c3a36fab1085cf8.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-2cc1781d1b9a07fd.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-9e99b6830b9b39fb.rlib" "C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-d4d285127ad54f3d.rlib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "ntdll.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\Mirro\\AppData\\Local\\Temp\\pip-install-01uskn36\\rtoml_4c0e12505933465598c2aeda4980008a\\target\\release\\build\\windows_x86_64_msvc-6b4fb174ad3d4709\\build_script_build-6b4fb174ad3d4709.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\Mirro\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" 
        = note: link: extra operand 'C:\\Users\\Mirro\\AppData\\Local\\Temp\\pip-install-01uskn36\\rtoml_4c0e12505933465598c2aeda4980008a\\target\\release\\build\\windows_x86_64_msvc-6b4fb174ad3d4709\\build_script_build-6b4fb174ad3d4709.build_script_build.b126910fc4f5e3e8-cgu.0.rcgu.o'
```
```

**Comment by LukasVik** [comment]
I think it would be very good if there could be a new rtoml release made which includes the wheel for 64-bit Windows. I have started to get bug reports in https://github.com/hdl-registers/hdl-registers about pip install failing on Windows due to the dependency.

There are currently 322 projects on GitHub alone that use rtoml (https://github.com/samuelcolvin/rtoml/network/dependents). Releasing rtoml with Windows64 support reinstated would save a lot of confusion and bug reports.

**Comment by mtessmer** [comment]
I would like to second @LukasVik's request for another release to fix 64bit Windows installs. I am giving a tutorial on my package that depends on rtoml in a couple of weeks and it would be a lot better if my Windows users could install and update without issues or workarounds.

**Comment by mtessmer** [comment]
I also want to point out that there is no earlier version of rtoml for Python 3.12 on Windows. This means Python 3.12 users on Windows can't install rtoml without installing rust and Visual C build tools. This is likely a large hurdle for beginners and so all 322 packages that depend on rtoml are effectively broken for new users on Windows.

**Comment by zerocewl** [comment]
@samuelcolvin Can you please generate a new release? maybe a patch e.g. `0.10.1` is enough?

**Comment by samuelcolvin** [comment]
Turns out this is not as simple as triggering a release, due to https://github.com/PyO3/maturin/issues/2110. I think there's a workaround, see #79.

**Comment by samuelcolvin** [comment]
v0.11 is released, see https://pypi.org/project/rtoml/

**Comment by LukasVik** [comment]
Great, thank you so much @samuelcolvin!
